/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate pipeline YAML
         * @description Validates a Benthos/Expanso pipeline YAML configuration against ground truth schema. Returns detected hallucinations with severity, corrections, and contextual messages.
         */
        post: operations["validatePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component schema
         * @description Returns the ground truth schema for Benthos/Expanso pipeline components. Can return full schema or filter by component type/name.
         */
        get: operations["getSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Component matching examples
         * @description Returns examples of fuzzy component name matching. Useful for understanding how typos are corrected.
         */
        get: operations["getComponents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns service health status
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI specification
         * @description Returns this OpenAPI 3.1 specification document
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description JSON request body for validation */
        ValidateRequest: {
            /** @description YAML pipeline configuration to validate */
            yaml: string;
            /**
             * @description Return formatted YAML
             * @default false
             */
            format: boolean;
            /**
             * @description Attempt auto-correction of hallucinations
             * @default false
             */
            auto_correct: boolean;
        };
        /** @description Validation result with detected hallucinations */
        ValidateResponse: {
            /** @description True if no ERROR-severity hallucinations were found */
            valid: boolean;
            /** @description Number of ERROR-severity hallucinations */
            error_count: number;
            /** @description List of detected hallucinations */
            hallucinations: components["schemas"]["Hallucination"][];
            /** @description Auto-corrected YAML (only if auto_correct=true and corrections were made) */
            corrected_yaml?: string;
            /** @description Formatted YAML (only if format=true) */
            formatted_yaml?: string;
            /** @description List of corrections applied (only if auto_correct=true) */
            corrections_made?: string[];
        };
        /** @description A detected hallucination in the pipeline configuration */
        Hallucination: {
            category: components["schemas"]["HallucinationType"];
            severity: components["schemas"]["Severity"];
            /** @description JSON path to the problematic element (e.g., 'input.kafka.brokrs') */
            path: string;
            /** @description The hallucinated/incorrect value */
            hallucination: string;
            /** @description Suggested correction (null if no suggestion available) */
            correction?: string | null;
            /** @description Human-readable error message */
            message: string;
            /** @description Line number in the YAML where the issue was found */
            line?: number | null;
            /** @description Surrounding code context for the error */
            context?: string | null;
        };
        /**
         * @description Category of hallucination detected
         * @enum {string}
         */
        HallucinationType: "IMAGINED_COMPONENT" | "IMAGINED_FIELD" | "IMAGINED_STRUCTURE" | "IMAGINED_SYNTAX" | "WRONG_TYPE" | "DUPLICATE_LABEL" | "UNDEFINED_RESOURCE" | "UNKNOWN";
        /**
         * @description Severity level of the hallucination
         * @enum {string}
         */
        Severity: "ERROR" | "WARNING" | "INFO";
        /** @description Summary of available schema with component counts */
        SchemaSummary: {
            title?: string;
            version?: string;
            /** @description Where the schema was harvested from */
            source?: string;
            /** Format: date-time */
            harvested_at?: string;
            component_types?: {
                type?: string;
                count?: number;
            }[];
            /** @description API usage examples */
            usage?: Record<string, never>;
        };
        /** @description Complete component schema */
        SchemaFull: {
            $schema?: string;
            title?: string;
            version?: string;
            components?: {
                [key: string]: {
                    [key: string]: components["schemas"]["ComponentSchema"];
                };
            };
        };
        /** @description Schema for a single pipeline component */
        ComponentSchema: {
            fields?: {
                [key: string]: components["schemas"]["FieldSchema"];
            };
            /** @description List of required field names */
            required?: string[];
        };
        /** @description Schema for a component field */
        FieldSchema: {
            /**
             * @description Field value type
             * @enum {string}
             */
            type?: "string" | "number" | "boolean" | "object" | "array";
            /** @description Whether the field is optional */
            optional?: boolean;
            /** @description Whether the field is deprecated */
            deprecated?: boolean;
            /** @description Whether this is an advanced configuration option */
            advanced?: boolean;
            /** @description Whether this field contains sensitive data */
            secret?: boolean;
            /** @description Child field names for object types */
            children?: string[];
            /** @description Type of array items */
            items_type?: string;
        };
        ComponentsResponse: {
            message?: string;
            fuzzy_matching_examples?: {
                input?: string;
                suggestion?: string | null;
            }[];
        };
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validatePipeline: {
        parameters: {
            query?: {
                /** @description Return formatted YAML in response */
                format?: boolean;
                /** @description Attempt to auto-correct common hallucinations */
                auto_correct?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example input:
                 *       kafka:
                 *         addresses: [localhost:9092]
                 *         topics: [events]
                 *     output:
                 *       stdout: {}
                 */
                "text/plain": string;
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation passed - no errors found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Invalid request (missing YAML) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed - hallucinations detected */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: {
                /** @description Filter by component type */
                type?: "inputs" | "outputs" | "processors" | "caches" | "rate_limits" | "buffers" | "scanners" | "metrics" | "tracers";
                /** @description Get specific component schema (requires type parameter) */
                component?: string;
                /** @description Return complete schema including all components */
                full?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaSummary"] | components["schemas"]["SchemaFull"] | components["schemas"]["ComponentSchema"];
                };
            };
        };
    };
    getComponents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Component matching examples */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentsResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
