---
id: azure-queue-storage-input
name: Azure Queue Storage Input
description: Consume messages from Azure Queue Storage
keywords:
  - azure
  - queue
  - storage
  - input
  - consume
  - messages
  - microsoft
components:
  inputs:
    - azure_queue_storage
  processors:
    - mapping
  outputs:
    - stdout
bloblangPatterns:
  - parse_json()
  - now()
  - env()
---
input:
  azure_queue_storage:
    storage_account: mystorageaccount
    storage_access_key: ${! env("AZURE_STORAGE_KEY") }
    queue_name: my-queue

pipeline:
  processors:
    - mapping: |
        root = this.parse_json()
        root.received_at = now()

output:
  stdout: {}
