---
id: datetime-conversion
name: DateTime Conversion (UTC to Local)
description: Convert timestamps between UTC and local time formats
keywords:
  - datetime
  - timestamp
  - utc
  - local
  - timezone
  - convert
  - format
components:
  inputs:
    - kafka
  processors:
    - mapping
  outputs:
    - kafka
bloblangPatterns:
  - ts_parse()
  - ts_format()
---
input:
  kafka:
    addresses: [localhost:9092]
    topics: [events]

pipeline:
  processors:
    - mapping: |
        root = this
        root.local_time = this.utc_time.ts_parse("2006-01-02T15:04:05Z").ts_format("2006-01-02 15:04:05", "Local")
        root.formatted = this.timestamp.ts_parse("RFC3339").ts_format("Jan 02, 2006 3:04 PM")

output:
  kafka:
    addresses: [localhost:9092]
    topic: formatted-events
