/**
 * Build script to compile YAML examples into a TypeScript data file.
 * This runs at build time to inline all examples into the bundle.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parseExampleFile } from '../src/examples-loader';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EXAMPLES_DIR = path.join(__dirname, '..', 'examples');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'examples-data.ts');

function main() {
  const files = fs.readdirSync(EXAMPLES_DIR).filter(f => f.endsWith('.yaml'));
  const examples: Array<{
    id: string;
    name: string;
    description: string;
    keywords: string[];
    components: { inputs: string[]; processors: string[]; outputs: string[] };
    bloblangPatterns: string[];
    yaml: string;
  }> = [];

  console.log(`Loading ${files.length} example files...`);

  for (const file of files) {
    const content = fs.readFileSync(path.join(EXAMPLES_DIR, file), 'utf-8');
    const parsed = parseExampleFile(content);
    if (parsed) {
      examples.push(parsed);
    } else {
      console.warn(`Warning: Could not parse ${file}`);
    }
  }

  // Sort by id for consistency
  examples.sort((a, b) => a.id.localeCompare(b.id));

  // Generate TypeScript file
  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by scripts/build-examples.ts from examples/*.yaml
 * Run 'npm run build:examples' to regenerate.
 */

import type { PipelineExample } from './examples-registry';

export const PIPELINE_EXAMPLES: PipelineExample[] = ${JSON.stringify(examples, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE} with ${examples.length} examples`);
}

main();
